# Generated by Django 4.2.2 on 2023-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certification',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
