# Generated by Django 4.2.2 on 2023-06-28 09:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certification_pic',
            field=models.ImageField(default='user_profile/usrDefaultImage.png', upload_to=accounts.models.get_file_path_user),
        ),
    ]
