# Generated by Django 4.2.2 on 2023-06-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_certification_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='certification',
        ),
    ]
