# Generated by Django 4.2.2 on 2023-06-28 09:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certification',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='certification_pic',
            field=models.ImageField(null=True, upload_to=accounts.models.get_file_path_user),
        ),
    ]
