# Generated by Django 4.2.1 on 2023-06-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='certification',
        ),
        migrations.AlterField(
            model_name='profile',
            name='certification_pic',
            field=models.ImageField(null=True, upload_to='certification/'),
        ),
    ]
