# Generated by Django 4.2.2 on 2023-06-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_somd_backgroundimage_alter_somd_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralram',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
